version: "3.8"

networks:
    brewdict-network:
        name: brewdict

volumes:
    data:
        name: db-data

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: mlbarker/brewdict-api:latest
        container_name: brewdict-api
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            brewdict-network:
                aliases:
                    - api

    nginx:
        image: nginx:alpine
        container_name: api-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            brewdict-network:
                aliases:
                    - nginx
