version: "3.8"

networks:
    brewdict-network:
        name: brewdict

volumes:
    db-data:
    nginx-certs:
    vhost:
    html:
    acme:


services:
    proxy:
      image: nginxproxy/nginx-proxy:alpine
      container_name: nginx-proxy
      restart: always
      ports:
        - 80:80
        - 443:443
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - nginx-certs:/etc/nginx/certs
        - vhost:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
      networks:
        brewdict-network:
          aliases:
            - proxy

    cert-service:
      image: nginxproxy/acme-companion
      container_name: nginx-cert
      restart: always
      volumes_from:
        - proxy
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - acme:/etc/acme.sh
      environment:
        - DEFAULT_EMAIL=hello@maxbarker.uk

#    db:
#      container_name: brewdict-mariadb
#      image: mariadb
#      depends_on:
#        - proxy      
#      restart: unless-stopped
#      ports:
#        - 3306:3306
#      volumes:
#        - ./docker-compose/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
#      networks:
#        brewdict-network:
#          aliases:
#            - db
#      environment:
#        - VIRTUAL_HOST=db.brewdict.io
#        - MYSQL_ROOT_PASSWORD=password
#        - MYSQL_ROOT_HOST=localhost    

    api:
        build:
            context: ./
            dockerfile: Dockerfile
        image: mlbarker/brewdict-api:latest
        container_name: brewdict-api      
        depends_on:
          - nginx
#        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            brewdict-network:
                aliases:
                    - api

    nginx:
        image: nginx:alpine
        container_name: api-nginx
        depends_on:
          - proxy
          - cert-service
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            brewdict-network:
                aliases:
                    - nginx
        environment:
          - VIRTUAL_HOST=api.brewdict.io
          - LETSENCRYPT_HOST=api.brewdict.io
