version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: mlbarker/brewdict-api:latest
    container_name: brewdict-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - brewdict

  nginx:
    image: nginx:alpine
    container_name: webserver-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - brewdict

networks:
  brewdict:
    driver: bridge
